// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fkhcboxjgijwyqbqxtpy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZraGNib3hqZ2lqd3lxYnF4dHB5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ4MzMwMjIsImV4cCI6MjA2MDQwOTAyMn0.OjSVGOJJQS97i7gPVYY2G6Ue_Ttg5O-bfi-pKITlvZA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);